kind: workflow
trigger:
  kind: OnConversationStart
  id: trigger_wf
  actions:
    - kind: InvokeAzureAgent
      id: agent1
      agent:
        name: Wishlist-Agent
        instructions: |
          You are the Wishlist-Agent for Secret Santa. Ask each participant for:
          Please share your holiday wishlist, favorite hobbies, or dream gifts!
          Collect each response and pass it on.
      description: Collect wishlists from participants for Secret Santa
      conversationId: =System.ConversationId
      input:
        messages: =System.LastMessage
      output:
        autoSend: true
        messages: Local.WishlistResponse
    - kind: InvokeAzureAgent
      id: agent2
      agent:
        name: Assignment-Agent
        instructions: |
          You are the Assignment Agent for Secret Santa.
          Randomly assign each participant a Secret Santa recipient.
          Ensure fairness: no self-assignment and no duplicates.
      description: Randomly assign Santas
      conversationId: =System.ConversationId
      input:
        messages: =Local.WishlistResponse
      output:
        messages: Local.AssignmentResult
        autoSend: true
    - kind: InvokeAzureAgent
      id: agent3
      agent:
        name: Reminders-Agent
        instructions: |
          You are the Notification Agent for Secret Santa.
          For each gifter, send a friendly message with their assigned recipient and gift hints.
      description: Notifies each gifter of their recipient
      conversationId: =System.ConversationId
      input:
        messages: =Local.AssignmentResult
      output:
        messages: Local.NotificationResult
        autoSend: true
    - kind: ConditionGroup
      conditions:
        - condition: =Not(IsBlank(Local.NotificationResult))
          actions:
            - kind: SendActivity
              activity: Secret Santa assignments complete! Notifications sent.
              id: action-1765229924855
          id: if-action-1765227341629-0
      id: action-1765227341629
      elseActions: []
id: secret-santa-workflow
name: Secret-Santa-Workflow
description: Handle Secret Santa wishlists, assignments, and notifications
