{
    "definition": {
        "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
        "contentVersion": "1.0.0.0",
        "triggers": {
            "When_an_HTTP_request_is_received": {
                "type": "Request",
                "kind": "Http",
                "inputs": {
                    "method": "POST",
                    "schema": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": "string"
                            },
                            "properties": {
                                "type": "object",
                                "properties": {
                                    "to": {
                                        "type": "object",
                                        "properties": {
                                            "type": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "subject": {
                                        "type": "object",
                                        "properties": {
                                            "type": {
                                                "type": "string"
                                            }
                                        }
                                    },
                                    "body": {
                                        "type": "object",
                                        "properties": {
                                            "type": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "actions": {
            "Send_an_email_(V2)": {
                "runAfter": {},
                "type": "ApiConnection",
                "inputs": {
                    "host": {
                        "connection": {
                            "name": "@parameters('$connections')['outlook']['connectionId']"
                        }
                    },
                    "method": "post",
                    "body": {
                        "To": "@triggerBody()?['to']",
                        "Subject": "@triggerBody()?['subject']",
                        "Body": "<p class=\"editor-paragraph\">@{triggerBody()?['body']\n}</p>",
                        "Importance": "Normal"
                    },
                    "path": "/v2/Mail"
                }
            },
            "Response": {
                "runAfter": {
                    "Send_an_email_(V2)": [
                        "Succeeded"
                    ]
                },
                "type": "Response",
                "kind": "Http",
                "inputs": {
                    "statusCode": 200,
                    "body": {
                        "status": "success"
                    }
                }
            }
        },
        "outputs": {},
        "parameters": {
            "$connections": {
                "type": "Object",
                "defaultValue": {}
            }
        }
    },
    "parameters": {
        "$connections": {
            "type": "Object",
            "value": {
                "outlook": {
                    "id": "/subscriptions/64681aa1-73cc-4155-aa97-caa0e4837412/providers/Microsoft.Web/locations/eastus/managedApis/outlook",
                    "connectionId": "/subscriptions/64681aa1-73cc-4155-aa97-caa0e4837412/resourceGroups/FestiveTechCalender2025-Demo/providers/Microsoft.Web/connections/outlook",
                    "connectionName": "outlook",
                    "connectionProperties": {}
                }
            }
        }
    }
}